### ISSUE TITLE
fromFloats and toFloats are not reversible

### ISSUE THREAD

**Issue by vorg** [imbcmdth/hdr#3]
I'm trying to get row RGBE byte values instead of floats so I used `fromFloats` but I'm getting unexpected results. So tried the code below. I know I should loose a bit of precision in the conversion but 233 and 59777 is a bit far from each other.

```javascript
var fromFloats = require('hdr/lib/color').fromFloats;
var toFloats = require('hdr/lib/color').toFloats;
var a = [233, 53, 134, 16];
var floats = toFloats(a[0], a[1], a[2], a[3]);
console.log(fromFloats(floats[0], floats[1], floats[2]));
//-> [ 59775, 13695, 34431, 8 ]
```

**Comment by imbcmdth** [comment]
Note that HDR version 0.6.x uses the mmme-encoding module which has a different calling style. I am going to use that module below.

It is in fact reversible. There may have been a bug with the older 'lib/color' code but the `mmme-encoding` library does a great job here:

```javascript
var fromFloats = require('mmme-encoding').fromFloats;
var toFloats = require('mmme-encoding').toFloats;
var a = [233, 53, 134, 16];
var floats = toFloats(a, []);
console.log(fromFloats(floats, []));
//-> [ 116, 26, 67, 17 ]
```

The final result is very nearly the same as the input - the mantissa's are all halved but the exponent is one greater (so the final floating point result will be within the encoding's rounding error.)

The best way to achieve what you want is to create a new constructor that `util.inherits` from `HDRLoader`. Then you can override the `_allocateData ` function to create an `Uint8ClampedArray` that is `width * height * 4` elements in size. Then override the `_processScanline ` function and get rid of the whole conversion to floats and the convserion to `XYZ` so that you keep RGBE just remove those 4 lines). Finally, override the _writePixel function to store all 4 elements of RGBE into the typed-array.

This way you won't lose any precision (you'll have the exact values in the file) and you'll not waste time doing needless conversion!
